@echo off
setlocal EnableDelayedExpansion

:: ===========================================================================
:: build.bat - Shell build for the T1S<->100BASE-T bridge firmware.
::
:: Unlike the lan866x-tools sibling project, this is a PLAIN MPLAB X project
:: (no CMake scaffold). It drives MPLAB X's own generated NetBeans-style
:: Makefile (nbproject/Makefile-impl.mk etc.) via MPLAB X's bundled 'make',
:: the same mechanism the IDE itself uses under the hood.
::
:: ONE-TIME PREREQUISITE: those nbproject Makefile fragments do not exist in
:: a fresh checkout - MPLAB X generates them the first time the project is
:: opened and built in the IDE. If this script reports them missing:
::   1. Open MPLAB X IDE -> File -> Open Project -> select
::      firmware\T1S_100BaseT_Bridge.X
::   2. Right-click the project -> Clean and Build (once)
:: After that, this script can drive incremental/headless builds.
::
:: Tool setup (once per machine):
::     install_dependencies.bat       (pyserial for the python tools)
::     python setup_compiler.py       (pick the installed XC32 version)
::     install.bat --install          (pyOCD for flash.bat)
::     python setup_debug.py          (SAME54_DFP tool-pack fix for VS Code)
:: Then:
::     build.bat [incremental|clean|rebuild|help]
::     flash.bat
:: ===========================================================================

set "SCRIPT_DIR=%~dp0"
set "MPLAB_DIR=%SCRIPT_DIR%firmware\T1S_100BaseT_Bridge.X"
set "PROJ_NAME=T1S_100BaseT_Bridge"
set "CONF=default"
set "TYPE_IMAGE=PRODUCTION"
set "DIST_DIR=%MPLAB_DIR%\dist\%CONF%\production"
set "ELF_PATH=%DIST_DIR%\%PROJ_NAME%.X.production.elf"
set "HEX_PATH=%DIST_DIR%\%PROJ_NAME%.X.production.hex"
set "COMPILER_CONFIG=%SCRIPT_DIR%setup_compiler.config"
set "MPLABX_MAKE="
for /f "delims=" %%D in ('dir /b /ad /o-n "C:\Program Files\Microchip\MPLABX\v*" 2^>nul') do (
    if not defined MPLABX_MAKE if exist "C:\Program Files\Microchip\MPLABX\%%D\gnuBins\GnuWin32\bin\make.exe" (
        set "MPLABX_MAKE=C:\Program Files\Microchip\MPLABX\%%D\gnuBins\GnuWin32\bin\make.exe"
    )
)

if not exist "%MPLAB_DIR%\nbproject\Makefile-impl.mk" (
    echo ERROR: nbproject Makefile fragments not found under:
    echo        %MPLAB_DIR%\nbproject\
    echo.
    echo        These are generated by MPLAB X itself and are not part of a
    echo        fresh checkout. One-time fix:
    echo          1. Open MPLAB X IDE
    echo          2. File -^> Open Project -^> %MPLAB_DIR%
    echo          3. Right-click the project -^> Clean and Build ^(once^)
    echo        After that, re-run this script.
    exit /b 1
)

if not defined MPLABX_MAKE (
    echo ERROR: Could not find MPLAB X's bundled make.exe under
    echo        C:\Program Files\Microchip\MPLABX\v*\gnuBins\GnuWin32\bin\
    echo        Install MPLAB X IDE.
    exit /b 1
)
echo Make      : %MPLABX_MAKE%

set "MP_CC_DIR_ARG="
if exist "%COMPILER_CONFIG%" (
    for /f "usebackq delims=" %%D in (`powershell -NoProfile -Command "(Get-Content '%COMPILER_CONFIG%' | ConvertFrom-Json).bin_dir"`) do set "XC32_BIN_DIR=%%D"
    if defined XC32_BIN_DIR (
        echo Compiler  : %XC32_BIN_DIR%
        set "MP_CC_DIR_ARG=MP_CC_DIR=%XC32_BIN_DIR%"
    )
) else (
    echo WARNING: No compiler configured ^(run "python setup_compiler.py"^).
    echo          Falling back to whatever MPLAB X's Makefile has baked in.
)

set "MODE=incremental"
if not "%~1"=="" set "MODE=%~1"
if /i "%MODE%"=="help"        goto :help
if /i "%MODE%"=="clean"       goto :clean
if /i "%MODE%"=="rebuild"     goto :rebuild
if /i "%MODE%"=="incremental" goto :incremental
echo ERROR: Unknown parameter "%~1"
goto :help

:help
echo Usage: build.bat [incremental^|clean^|rebuild^|help]
echo   (no argument)  Incremental build (default)
echo   clean          Delete all build artifacts for this configuration
echo   rebuild        Clean then perform a full build
exit /b 0

:clean
echo Cleaning (make clean, CONF=%CONF%)...
pushd "%MPLAB_DIR%"
"%MPLABX_MAKE%" -f Makefile CONF=%CONF% TYPE_IMAGE=%TYPE_IMAGE% clean
popd
exit /b 0

:rebuild
call :clean
goto :build

:incremental
:build
echo [1/1] Building (make, CONF=%CONF%, TYPE_IMAGE=%TYPE_IMAGE%)...
pushd "%MPLAB_DIR%"
"%MPLABX_MAKE%" -f Makefile CONF=%CONF% TYPE_IMAGE=%TYPE_IMAGE% %MP_CC_DIR_ARG% build
set "BUILD_RC=%errorlevel%"
popd
if not "%BUILD_RC%"=="0" ( echo ERROR: Build failed. & exit /b 1 )

echo.
echo BUILD SUCCESSFUL.
if exist "%HEX_PATH%" (
    echo HEX: %HEX_PATH%
    rem Copy the HEX into a tracked release dir so a fresh clone can flash
    rem without building - dist/ is gitignored.
    if not exist "%SCRIPT_DIR%release" mkdir "%SCRIPT_DIR%release"
    copy /Y "%HEX_PATH%" "%SCRIPT_DIR%release\T1S_100BaseT_Bridge.hex" >nul
    echo Released: %SCRIPT_DIR%release\T1S_100BaseT_Bridge.hex
) else (
    echo WARNING: expected HEX not found at %HEX_PATH%
)

rem Post-build memory / interrupt summary (flash/RAM, heap, IRQ handlers).
if exist "%ELF_PATH%" python "%SCRIPT_DIR%build_summary.py" "%DIST_DIR%" "%ELF_PATH%" "%XC32_BIN_DIR%"
endlocal
