#!/usr/bin/env python3
"""
iPerf PTP Test Agent for T1S 100BaseT Bridge
=============================================
Tests PTP (Precision Time Protocol) convergence and offset stability under
network load generated by iPerf UDP traffic.  Two ATSAME54P20A / LAN865x
boards connected via a 10BASE-T1S network are controlled through their serial
CLI interfaces.

Test Sequence
-------------
0. Reset both boards
1. Configure IP addresses (GM and Follower)
2. Verify bidirectional network connectivity (ping)
3. Start PTP Follower on the follower board
4. Start iPerf server on the follower board
5. Start iPerf client on the GM board (generates UDP load)
6. Start PTP Grandmaster on the GM board
7. Monitor convergence to FINE state while iPerf is running
8. Collect offset samples during iPerf load (validate ±100 ns threshold)
9. Stop iPerf on both boards
10. Verify PTP stability after iPerf stops (additional offset samples)
11. Cleanup (stop PTP on both boards, close ports)

Usage
-----
::

    # Basic run with default ports
    python tests/iperf_ptp_test_agent.py --gm-port COM10 --fol-port COM8

    # Custom bandwidth and duration
    python tests/iperf_ptp_test_agent.py --gm-port COM10 --fol-port COM8 \\
        --iperf-bandwidth 10M --iperf-duration 60

    # Verbose output with custom log file
    python tests/iperf_ptp_test_agent.py --gm-port COM10 --fol-port COM8 \\
        --verbose --log-file iperf_ptp_run1.log

    # Skip reset and IP config (resume from step 3)
    python tests/iperf_ptp_test_agent.py --gm-port COM10 --fol-port COM8 \\
        --from-step 3

Requirements
------------
::

    pip install pyserial
"""

import argparse
import datetime
import re
import statistics
import sys
import time
from typing import Dict, List, Optional, Tuple

try:
    import serial
except ImportError:
    print("ERROR: pyserial not installed. Run: pip install pyserial")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_GM_PORT = "COM10"
DEFAULT_FOL_PORT = "COM8"
DEFAULT_GM_IP = "192.168.0.20"
DEFAULT_FOL_IP = "192.168.0.30"
DEFAULT_NETMASK = "255.255.255.0"
DEFAULT_BAUDRATE = 115200
DEFAULT_CMD_TIMEOUT = 5        # seconds
DEFAULT_CONVERGENCE_TIMEOUT = 30  # seconds
DEFAULT_SAMPLES = 20
DEFAULT_POST_IPERF_SAMPLES = 20
OFFSET_THRESHOLD_NS = 100      # nanoseconds

# iPerf defaults
DEFAULT_IPERF_BANDWIDTH = "10M"   # e.g. "1M", "10M", "100M"
DEFAULT_IPERF_DURATION = 30       # seconds
DEFAULT_IPERF_PORT = 5001

# Regex patterns for CLI response parsing
RE_IP_SET = re.compile(r"IP address set to")
RE_PING_REPLY = re.compile(r"Reply from")
RE_FOL_START = re.compile(r"\[PTP\] follower mode")
RE_GM_START = re.compile(r"\[PTP\] grandmaster mode")
RE_MATCHFREQ = re.compile(r"UNINIT->MATCHFREQ")
RE_HARD_SYNC = re.compile(r"Hard sync completed")
RE_COARSE = re.compile(r"PTP COARSE")
RE_FINE = re.compile(r"PTP FINE")
RE_PTP_OFFSET = re.compile(r"\[PTP\] offset=([+-]?\d+)\s*ns")
RE_PTP_STATUS = re.compile(
    r"\[PTP\]\s+mode=(\S+)\s+gmSyncs=(\d+)\s+gmState=(\d+)"
)
RE_PTP_DISABLED = re.compile(r"\[PTP\] disabled")
RE_IPERF_SERVER_STARTED = re.compile(
    r"(?i)(iperf.*listen|server.*listen|iperf.*start|iperf.*ready|Server listening)"
)
RE_IPERF_CLIENT_STARTED = re.compile(
    r"(?i)(iperf.*connect|Client connect|iperf.*start|Connecting to)"
)
RE_IPERF_STOPPED = re.compile(
    r"(?i)(iperf.*stop|iperf.*done|iperf.*end|iperf.*finish)"
)


# ---------------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------------

class Logger:
    """Dual-writes to stdout and an optional log file."""

    def __init__(self, log_file: str = None, verbose: bool = False):
        self.log_file = log_file
        self.verbose = verbose
        self._fh = None
        if log_file:
            self._fh = open(log_file, "w", encoding="utf-8")

    def _write(self, line: str):
        print(line)
        if self._fh:
            self._fh.write(line + "\n")
            self._fh.flush()

    def info(self, msg: str):
        self._write(msg)

    def debug(self, msg: str):
        if self.verbose:
            self._write(f"  [DBG] {msg}")

    def close(self):
        if self._fh:
            self._fh.close()
            self._fh = None


# ---------------------------------------------------------------------------
# Serial helpers
# ---------------------------------------------------------------------------

def open_port(port: str, baudrate: int = DEFAULT_BAUDRATE) -> serial.Serial:
    """Open a serial port with standard 8N1 settings.

    Args:
        port: Port name, e.g. ``COM10`` or ``/dev/ttyUSB0``.
        baudrate: Baud rate (default 115200).

    Returns:
        Opened :class:`serial.Serial` instance.

    Raises:
        serial.SerialException: If the port cannot be opened.
    """
    ser = serial.Serial(
        port=port,
        baudrate=baudrate,
        bytesize=serial.EIGHTBITS,
        parity=serial.PARITY_NONE,
        stopbits=serial.STOPBITS_ONE,
        timeout=0.1,  # non-blocking reads; we poll manually
    )
    return ser


def send_command(
    ser: serial.Serial,
    cmd: str,
    timeout: float = DEFAULT_CMD_TIMEOUT,
    log: Logger = None,
) -> str:
    """Send a CLI command and collect the response.

    Sends *cmd* terminated by ``\\r\\n``, then reads until the timeout
    expires without new data.

    Args:
        ser: Open serial port.
        cmd: Command string (without line ending).
        timeout: Maximum seconds to wait for the response.
        log: Optional :class:`Logger` for debug output.

    Returns:
        Accumulated response string.
    """
    # Flush any stale data in the receive buffer.
    ser.reset_input_buffer()

    full_cmd = (cmd + "\r\n").encode("ascii")
    ser.write(full_cmd)
    if log:
        log.debug(f"  >> {cmd}")

    response_parts = []
    deadline = time.monotonic() + timeout
    last_data = time.monotonic()

    while time.monotonic() < deadline:
        chunk = ser.read(256)
        if chunk:
            decoded = chunk.decode("ascii", errors="replace")
            response_parts.append(decoded)
            last_data = time.monotonic()
            if log:
                log.debug(decoded.rstrip())
        else:
            # Stop once the port has been quiet for 0.5 s after receiving data.
            if response_parts and (time.monotonic() - last_data) > 0.5:
                break
            time.sleep(0.05)

    response = "".join(response_parts)
    return response


def wait_for_pattern(
    ser: serial.Serial,
    pattern: "re.Pattern",
    timeout: float = DEFAULT_CONVERGENCE_TIMEOUT,
    log: Logger = None,
    extra_patterns: dict = None,
) -> tuple:
    """Read from *ser* until *pattern* matches or *timeout* expires.

    Args:
        ser: Open serial port.
        pattern: Compiled regex to wait for.
        timeout: Maximum wait time in seconds.
        log: Optional :class:`Logger` for debug output.
        extra_patterns: Mapping of label→compiled-regex for milestones to
            record (first-match timestamps returned in the result dict).

    Returns:
        A tuple ``(matched: bool, elapsed: float, milestones: dict)``.
        *milestones* maps label→elapsed-seconds for each extra pattern that
        was first matched.
    """
    if extra_patterns is None:
        extra_patterns = {}

    milestones: dict = {}
    buffer = ""
    start = time.monotonic()
    deadline = start + timeout

    while time.monotonic() < deadline:
        chunk = ser.read(256)
        if chunk:
            decoded = chunk.decode("ascii", errors="replace")
            buffer += decoded
            if log:
                for line in decoded.splitlines():
                    if line.strip():
                        log.debug(f"  <- {line.rstrip()}")

            for label, pat in extra_patterns.items():
                if label not in milestones and pat.search(buffer):
                    milestones[label] = time.monotonic() - start

            if pattern.search(buffer):
                elapsed = time.monotonic() - start
                return True, elapsed, milestones
        else:
            time.sleep(0.05)

    elapsed = time.monotonic() - start
    return False, elapsed, milestones


# ---------------------------------------------------------------------------
# Offset parsing
# ---------------------------------------------------------------------------

def parse_offset(response: str) -> Optional[int]:
    """Extract the offset value (in nanoseconds) from a ``ptp_offset`` response.

    Expected format: ``[PTP] offset=+45 ns  abs=45 ns``

    Args:
        response: Raw CLI response string.

    Returns:
        Integer offset in ns, or ``None`` if not found.
    """
    m = RE_PTP_OFFSET.search(response)
    if m:
        return int(m.group(1))
    return None


def parse_ptp_status(response: str) -> Optional[Dict]:
    """Parse the output of ``ptp_status``.

    Expected format: ``[PTP] mode=master gmSyncs=198 gmState=3``

    Args:
        response: Raw CLI response string.

    Returns:
        Dict with keys ``mode``, ``gmSyncs`` (int), ``gmState`` (int), or
        ``None`` if the pattern was not found.
    """
    m = RE_PTP_STATUS.search(response)
    if m:
        return {
            "mode": m.group(1),
            "gmSyncs": int(m.group(2)),
            "gmState": int(m.group(3)),
        }
    return None


def _collect_offset_samples(
    fol_ser: serial.Serial,
    num_samples: int,
    cmd_timeout: float,
    log: Logger,
    label: str = "",
) -> List[int]:
    """Query ``ptp_offset`` *num_samples* times and return parsed values.

    Args:
        fol_ser: Open serial port to the Follower board.
        num_samples: How many offset queries to perform.
        cmd_timeout: Per-command timeout in seconds.
        log: :class:`Logger` for status output.
        label: Optional context label shown in debug messages.

    Returns:
        List of integer offset values (ns) that were successfully parsed.
    """
    offsets: List[int] = []
    prefix = f"[{label}] " if label else ""
    for i in range(num_samples):
        resp = send_command(fol_ser, "ptp_offset", cmd_timeout, log)
        value = parse_offset(resp)
        if value is not None:
            offsets.append(value)
            log.debug(f"  {prefix}sample {i+1}/{num_samples}: {value:+d} ns")
        else:
            log.info(
                f"  {prefix}✗ Could not parse offset from: {resp.strip()!r}"
            )
        time.sleep(0.2)
    return offsets


def _compute_offset_stats(offsets: List[int]) -> Dict:
    """Compute summary statistics for a list of offset values.

    Args:
        offsets: List of integer offset values in nanoseconds.

    Returns:
        Dict with keys ``samples``, ``mean``, ``stdev``, ``min``, ``max``,
        ``within``, and ``pct``.
    """
    mean_val = statistics.mean(offsets)
    stdev_val = statistics.stdev(offsets) if len(offsets) > 1 else 0.0
    min_val = min(offsets)
    max_val = max(offsets)
    within = [v for v in offsets if abs(v) <= OFFSET_THRESHOLD_NS]
    pct = 100.0 * len(within) / len(offsets)
    return {
        "samples": len(offsets),
        "mean": mean_val,
        "stdev": stdev_val,
        "min": min_val,
        "max": max_val,
        "within": len(within),
        "pct": pct,
    }


# ---------------------------------------------------------------------------
# Test steps
# ---------------------------------------------------------------------------

class IperfPTPTestAgent:
    """Orchestrates the full iPerf+PTP test sequence.

    This agent starts a PTP Follower, launches an iPerf UDP server on the
    Follower board, an iPerf UDP client on the Grandmaster board, then starts
    the PTP Grandmaster.  It verifies that PTP converges to FINE state even
    under network load, validates offset accuracy during the load, stops
    iPerf, and validates continued stability afterwards.

    Args:
        gm_port: Serial port name for the Grandmaster board.
        fol_port: Serial port name for the Follower board.
        gm_ip: IP address to assign to the Grandmaster.
        fol_ip: IP address to assign to the Follower.
        netmask: Subnet mask (default ``255.255.255.0``).
        samples: Number of ``ptp_offset`` samples during iPerf load.
        post_iperf_samples: Number of ``ptp_offset`` samples after iPerf stops.
        convergence_timeout: Max seconds to wait for FINE state.
        cmd_timeout: Max seconds to wait for a single command response.
        iperf_bandwidth: iPerf target bandwidth string, e.g. ``"10M"``.
        iperf_duration: iPerf client run time in seconds.
        iperf_port: UDP port used by iPerf (default 5001).
        stop_ptp_after: If ``True`` (default), send ``ptp_mode off`` during cleanup.
        from_step: Skip steps with step number below this value.
        log: :class:`Logger` instance.
    """

    def __init__(
        self,
        gm_port: str,
        fol_port: str,
        gm_ip: str = DEFAULT_GM_IP,
        fol_ip: str = DEFAULT_FOL_IP,
        netmask: str = DEFAULT_NETMASK,
        samples: int = DEFAULT_SAMPLES,
        post_iperf_samples: int = DEFAULT_POST_IPERF_SAMPLES,
        convergence_timeout: float = DEFAULT_CONVERGENCE_TIMEOUT,
        cmd_timeout: float = DEFAULT_CMD_TIMEOUT,
        iperf_bandwidth: str = DEFAULT_IPERF_BANDWIDTH,
        iperf_duration: int = DEFAULT_IPERF_DURATION,
        iperf_port: int = DEFAULT_IPERF_PORT,
        stop_ptp_after: bool = True,
        from_step: int = 1,
        log: Logger = None,
    ):
        self.gm_port_name = gm_port
        self.fol_port_name = fol_port
        self.gm_ip = gm_ip
        self.fol_ip = fol_ip
        self.netmask = netmask
        self.samples = samples
        self.post_iperf_samples = post_iperf_samples
        self.convergence_timeout = convergence_timeout
        self.cmd_timeout = cmd_timeout
        self.iperf_bandwidth = iperf_bandwidth
        self.iperf_duration = iperf_duration
        self.iperf_port = iperf_port
        self.stop_ptp_after = stop_ptp_after
        self.from_step = from_step
        self.log = log or Logger()

        self.gm_ser: Optional[serial.Serial] = None
        self.fol_ser: Optional[serial.Serial] = None

        # Test results: (step_name, passed, detail)
        self.results: list = []
        # Offset statistics blocks populated by steps 8 and 10
        self._load_stats: Optional[Dict] = None
        self._post_iperf_stats: Optional[Dict] = None

    # ------------------------------------------------------------------
    # Connection management
    # ------------------------------------------------------------------

    def connect(self):
        """Open serial connections to both boards.

        Raises:
            SystemExit: On connection failure.
        """
        self.log.info(f"Connecting to GM  ({self.gm_port_name})…")
        try:
            self.gm_ser = open_port(self.gm_port_name)
            self.log.info(f"  GM  port open: {self.gm_port_name}")
        except serial.SerialException as exc:
            self.log.info(f"ERROR: Cannot open GM port {self.gm_port_name}: {exc}")
            sys.exit(1)

        self.log.info(f"Connecting to FOL ({self.fol_port_name})…")
        try:
            self.fol_ser = open_port(self.fol_port_name)
            self.log.info(f"  FOL port open: {self.fol_port_name}")
        except serial.SerialException as exc:
            self.log.info(f"ERROR: Cannot open FOL port {self.fol_port_name}: {exc}")
            if self.gm_ser:
                self.gm_ser.close()
            sys.exit(1)

    def disconnect(self):
        """Close serial ports gracefully."""
        for ser in (self.gm_ser, self.fol_ser):
            if ser and ser.is_open:
                try:
                    ser.close()
                except Exception:
                    pass

    # ------------------------------------------------------------------
    # Step 0 — Reset both boards
    # ------------------------------------------------------------------

    def test_step_0_reset(self):
        """Send a reset command to both boards and wait 8 seconds.

        Always executed regardless of ``--from-step``.  A failure to
        confirm the reset only produces a warning — the test continues.
        """
        step = "Step 0: Reset"
        self.log.info(f"\n--- {step} ---")

        detail_parts = []

        for label, ser in [("GM ", self.gm_ser), ("FOL", self.fol_ser)]:
            self.log.info(f"  [{label}] reset")
            try:
                resp = send_command(ser, "reset", self.cmd_timeout, self.log)
                detail_parts.append(f"{label} reset sent")
                self.log.info(f"  [{label}] ✓ reset command sent")
                if resp.strip():
                    self.log.debug(f"  [{label}] response: {resp.strip()!r}")
            except Exception as exc:
                detail_parts.append(f"{label} reset WARNING ({exc})")
                self.log.info(f"  [{label}] ⚠ reset failed (continuing): {exc}")

        self.log.info("  Waiting 8 s after reset…")
        time.sleep(8)

        self._record(step, True, "; ".join(detail_parts))

    # ------------------------------------------------------------------
    # Step 1 — IP configuration
    # ------------------------------------------------------------------

    def test_step_1_ip_config(self) -> bool:
        """Configure IP addresses on both boards.

        Sends ``setip eth0 <IP> <NETMASK>`` to each board and checks for the
        ``IP address set to`` confirmation message.

        Returns:
            ``True`` if both boards confirmed their IP address.
        """
        step = "Step 1: IP Configuration"
        self.log.info(f"\n--- {step} ---")

        passed = True
        detail_parts = []

        for label, ser, ip in [
            ("GM ", self.gm_ser, self.gm_ip),
            ("FOL", self.fol_ser, self.fol_ip),
        ]:
            cmd = f"setip eth0 {ip} {self.netmask}"
            self.log.info(f"  [{label}] {cmd}")
            resp = send_command(ser, cmd, self.cmd_timeout, self.log)
            if RE_IP_SET.search(resp):
                detail_parts.append(f"{label} IP ok ({ip})")
                self.log.info(f"  [{label}] ✓ IP set")
            else:
                detail_parts.append(f"{label} IP FAIL ({ip})")
                self.log.info(f"  [{label}] ✗ Unexpected response: {resp.strip()!r}")
                passed = False

        self._record(step, passed, "; ".join(detail_parts))
        return passed

    # ------------------------------------------------------------------
    # Step 2 — Network connectivity
    # ------------------------------------------------------------------

    def test_step_2_connectivity(self) -> bool:
        """Ping in both directions to verify network connectivity.

        Sends ``ping <IP>`` from each board to the other and checks for a
        ``Reply from`` confirmation.

        Returns:
            ``True`` if both pings replied.
        """
        step = "Step 2: Network Connectivity (GM→FOL, FOL→GM)"
        self.log.info(f"\n--- {step} ---")

        passed = True
        detail_parts = []

        for src_label, src_ser, dst_ip in [
            ("GM →FOL", self.gm_ser, self.fol_ip),
            ("FOL→GM ", self.fol_ser, self.gm_ip),
        ]:
            cmd = f"ping {dst_ip}"
            self.log.info(f"  [{src_label}] {cmd}")
            resp = send_command(src_ser, cmd, self.cmd_timeout, self.log)
            if RE_PING_REPLY.search(resp):
                detail_parts.append(f"{src_label} ok")
                self.log.info(f"  [{src_label}] ✓ Reply received")
            else:
                detail_parts.append(f"{src_label} FAIL")
                self.log.info(
                    f"  [{src_label}] ✗ No reply. Response: {resp.strip()!r}"
                )
                passed = False

        self._record(step, passed, "; ".join(detail_parts))
        return passed

    # ------------------------------------------------------------------
    # Step 3 — Start PTP Follower
    # ------------------------------------------------------------------

    def test_step_3_start_follower(self) -> bool:
        """Start PTP in Follower mode on the follower board.

        The follower must be running before the iPerf server is launched and
        before the Grandmaster starts.  This lets the follower begin listening
        for PTP packets as soon as the master appears.

        Returns:
            ``True`` if the follower confirmed ``[PTP] follower mode``.
        """
        step = "Step 3: Start PTP Follower"
        self.log.info(f"\n--- {step} ---")

        self.log.info("  [FOL] ptp_mode follower")
        resp = send_command(
            self.fol_ser, "ptp_mode follower", self.cmd_timeout, self.log
        )
        if RE_FOL_START.search(resp):
            detail = "FOL follower mode confirmed"
            self.log.info("  [FOL] ✓ follower mode confirmed")
            passed = True
        else:
            detail = f"FOL follower mode FAIL (resp={resp.strip()!r})"
            self.log.info(f"  [FOL] ✗ Unexpected response: {resp.strip()!r}")
            passed = False

        self._record(step, passed, detail)
        return passed

    # ------------------------------------------------------------------
    # Step 4 — Start iPerf server on Follower
    # ------------------------------------------------------------------

    def test_step_4_start_iperf_server(self) -> bool:
        """Start iPerf in server mode on the follower board.

        Sends ``iperf -s -u -p <port>`` to launch a UDP iPerf server.  Because
        the firmware command runs in the background (the board continues to
        respond to the CLI), a brief pause is included to allow the server to
        initialise before the client connects.

        If the firmware does not return a recognisable acknowledgement, a
        warning is logged but the step is still considered passed so that the
        test can continue — the client connection in Step 5 provides the real
        confirmation.

        Returns:
            ``True`` always (server-start errors are non-fatal; the client
            step acts as the functional check).
        """
        step = "Step 4: Start iPerf Server (FOL)"
        self.log.info(f"\n--- {step} ---")

        cmd = f"iperf -s -u -p {self.iperf_port}"
        self.log.info(f"  [FOL] {cmd}")
        resp = send_command(self.fol_ser, cmd, self.cmd_timeout, self.log)

        if RE_IPERF_SERVER_STARTED.search(resp):
            detail = f"iPerf server started on port {self.iperf_port}"
            self.log.info(f"  [FOL] ✓ {detail}")
        else:
            detail = (
                f"iPerf server cmd sent (port {self.iperf_port}); "
                f"no explicit confirmation — continuing"
            )
            self.log.info(
                f"  [FOL] ⚠ No explicit server-start confirmation. "
                f"Response: {resp.strip()!r}"
            )

        # Allow the server socket to open before the client connects.
        time.sleep(1)

        self._record(step, True, detail)
        return True

    # ------------------------------------------------------------------
    # Step 5 — Start iPerf client on GM
    # ------------------------------------------------------------------

    def test_step_5_start_iperf_client(self) -> bool:
        """Start iPerf in client mode on the Grandmaster board.

        Sends ``iperf -c <FOL_IP> -u -b <bandwidth> -t <duration>`` to
        generate a continuous UDP load towards the Follower for the configured
        duration.  The command is launched asynchronously (the firmware runs it
        in the background), so this step returns quickly.

        Returns:
            ``True`` if the client command was accepted (or if no explicit
            rejection was received).
        """
        step = "Step 5: Start iPerf Client (GM)"
        self.log.info(f"\n--- {step} ---")

        cmd = (
            f"iperf -c {self.fol_ip} -u "
            f"-b {self.iperf_bandwidth} "
            f"-t {self.iperf_duration} "
            f"-p {self.iperf_port}"
        )
        self.log.info(f"  [GM ] {cmd}")
        resp = send_command(self.gm_ser, cmd, self.cmd_timeout, self.log)

        if RE_IPERF_CLIENT_STARTED.search(resp):
            detail = (
                f"iPerf client started → {self.fol_ip}:{self.iperf_port} "
                f"bw={self.iperf_bandwidth} dur={self.iperf_duration}s"
            )
            self.log.info(f"  [GM ] ✓ {detail}")
            passed = True
        else:
            # The firmware may not echo a distinct confirmation; treat as
            # non-fatal to keep the test sequence going.
            detail = (
                f"iPerf client cmd sent → {self.fol_ip}:{self.iperf_port} "
                f"bw={self.iperf_bandwidth} dur={self.iperf_duration}s; "
                f"no explicit confirmation — continuing"
            )
            self.log.info(
                f"  [GM ] ⚠ No explicit client-start confirmation. "
                f"Response: {resp.strip()!r}"
            )
            passed = True  # non-fatal; PTP steps will reveal if traffic flows

        # Brief pause so traffic has time to establish before PTP starts.
        time.sleep(1)

        self._record(step, passed, detail)
        return passed

    # ------------------------------------------------------------------
    # Step 6 — Start PTP Grandmaster
    # ------------------------------------------------------------------

    def test_step_6_start_ptp_master(self) -> bool:
        """Start PTP in Grandmaster mode on the GM board.

        The grandmaster is started *after* iPerf traffic is already flowing so
        that convergence is tested under realistic network load conditions.

        Returns:
            ``True`` if the GM confirmed ``[PTP] grandmaster mode``.
        """
        step = "Step 6: Start PTP Grandmaster"
        self.log.info(f"\n--- {step} ---")

        self.log.info("  [GM ] ptp_mode master")
        resp = send_command(
            self.gm_ser, "ptp_mode master", self.cmd_timeout, self.log
        )
        if RE_GM_START.search(resp):
            detail = "GM grandmaster mode confirmed"
            self.log.info("  [GM ] ✓ grandmaster mode confirmed")
            passed = True
        else:
            detail = f"GM grandmaster mode FAIL (resp={resp.strip()!r})"
            self.log.info(f"  [GM ] ✗ Unexpected response: {resp.strip()!r}")
            passed = False

        self._record(step, passed, detail)
        return passed

    # ------------------------------------------------------------------
    # Step 7 — Convergence under iPerf load
    # ------------------------------------------------------------------

    def test_step_7_convergence_under_load(self) -> bool:
        """Monitor the Follower for convergence to FINE state while iPerf runs.

        Watches the Follower serial output for the state progression:
        ``UNINIT → MATCHFREQ → HARDSYNC → COARSE → FINE``

        The test succeeds only when ``PTP FINE`` appears within the configured
        timeout.  State-transition milestones are logged with their timestamps
        to aid debugging.

        Returns:
            ``True`` if FINE state was reached within ``convergence_timeout``.
        """
        step = "Step 7: Convergence to FINE (under iPerf load)"
        self.log.info(
            f"\n--- {step} (timeout={self.convergence_timeout}s) ---"
        )
        self.log.info(
            f"  iPerf load: bw={self.iperf_bandwidth}  "
            f"port={self.iperf_port}  dur={self.iperf_duration}s"
        )

        extra = {
            "MATCHFREQ": RE_MATCHFREQ,
            "HARD_SYNC": RE_HARD_SYNC,
            "COARSE": RE_COARSE,
        }

        matched, elapsed, milestones = wait_for_pattern(
            self.fol_ser,
            RE_FINE,
            timeout=self.convergence_timeout,
            log=self.log,
            extra_patterns=extra,
        )

        milestone_str = ", ".join(
            f"{k}@{v:.1f}s" for k, v in milestones.items()
        )
        if milestone_str:
            self.log.info(f"  Milestones: {milestone_str}")

        if matched:
            detail = (
                f"FINE reached in {elapsed:.1f}s under iPerf load "
                f"(bw={self.iperf_bandwidth})"
            )
            self.log.info(f"  ✓ {detail}")
        else:
            detail = (
                f"FINE NOT reached within {self.convergence_timeout}s "
                f"under iPerf load (milestones: {milestone_str or 'none'})"
            )
            self.log.info(f"  ✗ {detail}")

        self._record(step, matched, detail)
        return matched

    # ------------------------------------------------------------------
    # Step 8 — Offset validation under iPerf load
    # ------------------------------------------------------------------

    def test_step_8_offset_validation_under_load(self) -> bool:
        """Collect offset samples from the Follower while iPerf traffic runs.

        Queries ``ptp_offset`` *samples* times (0.2 s apart) and validates
        that every reading is within ±``OFFSET_THRESHOLD_NS`` ns.  Summary
        statistics are stored for the final report.

        Returns:
            ``True`` if all samples are within the threshold.
        """
        step = "Step 8: Offset Validation (under iPerf load)"
        self.log.info(
            f"\n--- {step} "
            f"(samples={self.samples}, threshold=±{OFFSET_THRESHOLD_NS}ns) ---"
        )

        offsets = _collect_offset_samples(
            self.fol_ser, self.samples, self.cmd_timeout, self.log,
            label="load",
        )

        if not offsets:
            self._record(step, False, "No valid offset samples collected")
            return False

        st = _compute_offset_stats(offsets)
        self._load_stats = st

        self.log.info(f"  Samples : {st['samples']}")
        self.log.info(f"  Mean    : {st['mean']:+.1f} ns")
        self.log.info(f"  Stdev   : {st['stdev']:.1f} ns")
        self.log.info(f"  Min     : {st['min']:+d} ns")
        self.log.info(f"  Max     : {st['max']:+d} ns")
        self.log.info(
            f"  Within ±{OFFSET_THRESHOLD_NS}ns: "
            f"{st['within']}/{st['samples']} ({st['pct']:.0f}%)"
        )

        passed = st["within"] == st["samples"]
        detail = (
            f"mean={st['mean']:+.1f}ns stdev={st['stdev']:.1f}ns "
            f"min={st['min']:+d}ns max={st['max']:+d}ns "
            f"within±{OFFSET_THRESHOLD_NS}ns: "
            f"{st['within']}/{st['samples']} ({st['pct']:.0f}%)"
        )

        self._record(step, passed, detail)
        return passed

    # ------------------------------------------------------------------
    # Step 9 — Stop iPerf
    # ------------------------------------------------------------------

    def test_step_9_stop_iperf(self) -> bool:
        """Stop iPerf on both boards.

        Sends ``iperf_stop`` to both boards.  If the firmware does not
        recognise the command or does not reply with a confirmation, a warning
        is logged but the step is treated as passed — the iPerf client will
        finish naturally when its ``-t`` duration expires.

        Returns:
            ``True`` always (stop failures are non-fatal; the timed client
            will terminate on its own).
        """
        step = "Step 9: Stop iPerf"
        self.log.info(f"\n--- {step} ---")

        detail_parts = []

        for label, ser in [("GM ", self.gm_ser), ("FOL", self.fol_ser)]:
            self.log.info(f"  [{label}] iperf_stop")
            try:
                resp = send_command(ser, "iperf_stop", self.cmd_timeout, self.log)
                if RE_IPERF_STOPPED.search(resp):
                    detail_parts.append(f"{label} iperf stopped")
                    self.log.info(f"  [{label}] ✓ iPerf stopped")
                else:
                    detail_parts.append(f"{label} iperf_stop sent (no explicit ack)")
                    self.log.info(
                        f"  [{label}] ⚠ No explicit stop confirmation. "
                        f"Response: {resp.strip()!r}"
                    )
            except Exception as exc:
                detail_parts.append(f"{label} iperf_stop WARNING ({exc})")
                self.log.info(f"  [{label}] ⚠ iperf_stop failed (continuing): {exc}")

        # Allow the network to settle before collecting post-iPerf samples.
        self.log.info("  Waiting 2 s for network to settle…")
        time.sleep(2)

        self._record(step, True, "; ".join(detail_parts))
        return True

    # ------------------------------------------------------------------
    # Step 10 — Post-iPerf stability check
    # ------------------------------------------------------------------

    def test_step_10_post_iperf_stability(self) -> bool:
        """Collect offset samples after iPerf has stopped to verify stability.

        After the network load disappears, PTP should remain in FINE state
        and offsets should stay within ±``OFFSET_THRESHOLD_NS`` ns.  This step
        gathers *post_iperf_samples* readings and validates them with the same
        threshold used during the load test.

        Returns:
            ``True`` if all post-iPerf samples are within the threshold.
        """
        step = "Step 10: Post-iPerf Stability"
        self.log.info(
            f"\n--- {step} "
            f"(samples={self.post_iperf_samples}, "
            f"threshold=±{OFFSET_THRESHOLD_NS}ns) ---"
        )

        offsets = _collect_offset_samples(
            self.fol_ser, self.post_iperf_samples, self.cmd_timeout, self.log,
            label="post-iperf",
        )

        if not offsets:
            self._record(step, False, "No valid offset samples collected")
            return False

        st = _compute_offset_stats(offsets)
        self._post_iperf_stats = st

        self.log.info(f"  Samples : {st['samples']}")
        self.log.info(f"  Mean    : {st['mean']:+.1f} ns")
        self.log.info(f"  Stdev   : {st['stdev']:.1f} ns")
        self.log.info(f"  Min     : {st['min']:+d} ns")
        self.log.info(f"  Max     : {st['max']:+d} ns")
        self.log.info(
            f"  Within ±{OFFSET_THRESHOLD_NS}ns: "
            f"{st['within']}/{st['samples']} ({st['pct']:.0f}%)"
        )

        passed = st["within"] == st["samples"]
        detail = (
            f"mean={st['mean']:+.1f}ns stdev={st['stdev']:.1f}ns "
            f"min={st['min']:+d}ns max={st['max']:+d}ns "
            f"within±{OFFSET_THRESHOLD_NS}ns: "
            f"{st['within']}/{st['samples']} ({st['pct']:.0f}%)"
        )

        self._record(step, passed, detail)
        return passed

    # ------------------------------------------------------------------
    # Optional — PTP status query
    # ------------------------------------------------------------------

    def check_ptp_status(self):
        """Query ``ptp_status`` on both boards and log the results."""
        self.log.info("\n--- PTP Status Check ---")
        for label, ser in [("GM ", self.gm_ser), ("FOL", self.fol_ser)]:
            resp = send_command(ser, "ptp_status", self.cmd_timeout, self.log)
            status = parse_ptp_status(resp)
            if status:
                self.log.info(
                    f"  [{label}] mode={status['mode']}  "
                    f"gmSyncs={status['gmSyncs']}  gmState={status['gmState']}"
                )
            else:
                self.log.info(
                    f"  [{label}] Could not parse ptp_status: {resp.strip()!r}"
                )

    # ------------------------------------------------------------------
    # Cleanup
    # ------------------------------------------------------------------

    def cleanup(self):
        """Optionally stop PTP on both boards, then close serial ports.

        If ``stop_ptp_after`` is ``True``, sends ``ptp_mode off`` to both
        boards before closing the ports.
        """
        if self.stop_ptp_after and self.gm_ser and self.fol_ser:
            self.log.info("\n--- Stopping PTP ---")
            for label, ser in [("GM ", self.gm_ser), ("FOL", self.fol_ser)]:
                resp = send_command(
                    ser, "ptp_mode off", self.cmd_timeout, self.log
                )
                if RE_PTP_DISABLED.search(resp):
                    self.log.info(f"  [{label}] ✓ PTP disabled")
                else:
                    self.log.info(
                        f"  [{label}] ✗ Unexpected: {resp.strip()!r}"
                    )
        self.disconnect()

    # ------------------------------------------------------------------
    # Run all steps
    # ------------------------------------------------------------------

    def run(self, start_time: datetime.datetime = None) -> int:
        """Execute all enabled test steps and print the final report.

        Steps below ``from_step`` (except Step 0, which always runs) are
        skipped.  The test aborts early if a critical step (≤ Step 6) fails.

        Args:
            start_time: Optional timestamp representing when the test run
                began.  If not provided, the current time is used.  Pass the
                same value used to generate the log-file name so that the
                report header and file name are consistent.

        Returns:
            ``0`` if all executed steps passed, ``1`` otherwise.
        """
        if start_time is None:
            start_time = datetime.datetime.now()

        self.log.info("=" * 60)
        self.log.info("  iPerf PTP Test Agent — T1S 100BaseT Bridge")
        self.log.info("=" * 60)
        self.log.info(f"Date          : {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
        self.log.info(f"GM Port       : {self.gm_port_name} ({self.gm_ip})")
        self.log.info(f"Follower      : {self.fol_port_name} ({self.fol_ip})")
        self.log.info(f"iPerf BW      : {self.iperf_bandwidth}")
        self.log.info(f"iPerf Duration: {self.iperf_duration} s")
        self.log.info(f"iPerf Port    : {self.iperf_port}")
        self.log.info(f"From step     : {self.from_step}")

        self.connect()

        try:
            # Step 0 is always executed regardless of from_step.
            self.test_step_0_reset()

            step_functions = [
                (1, self.test_step_1_ip_config),
                (2, self.test_step_2_connectivity),
                (3, self.test_step_3_start_follower),
                (4, self.test_step_4_start_iperf_server),
                (5, self.test_step_5_start_iperf_client),
                (6, self.test_step_6_start_ptp_master),
                (7, self.test_step_7_convergence_under_load),
                (8, self.test_step_8_offset_validation_under_load),
                (9, self.test_step_9_stop_iperf),
                (10, self.test_step_10_post_iperf_stability),
            ]

            for step_num, func in step_functions:
                if step_num < self.from_step:
                    self.log.info(f"\n(Skipping Step {step_num}: {func.__name__})")
                    continue
                passed = func()
                # Abort on failure of any critical setup step.
                if not passed and step_num <= 6:
                    self.log.info(
                        "\nAborting: early step failure — check hardware."
                    )
                    break

            self.check_ptp_status()

        except KeyboardInterrupt:
            self.log.info("\n\nInterrupted by user (Ctrl+C).")
        finally:
            self.cleanup()

        return self._print_report(start_time)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _record(self, name: str, passed: bool, detail: str):
        """Append a test result tuple to the internal results list."""
        self.results.append((name, passed, detail))

    def _print_report(self, start_time: datetime.datetime) -> int:
        """Print the final test report.

        Includes per-step pass/fail status, offset statistics during iPerf
        load, and offset statistics after iPerf stops.

        Returns:
            Exit code: ``0`` = all passed, ``1`` = any failed.
        """
        self.log.info("\n" + "=" * 60)
        self.log.info("  iPerf PTP Test Report")
        self.log.info("=" * 60)
        self.log.info(f"Date          : {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
        self.log.info(f"GM Port       : {self.gm_port_name} ({self.gm_ip})")
        self.log.info(f"FOL Port      : {self.fol_port_name} ({self.fol_ip})")
        self.log.info(f"iPerf BW      : {self.iperf_bandwidth}")
        self.log.info(f"iPerf Duration: {self.iperf_duration} s")
        self.log.info(f"iPerf Port    : {self.iperf_port}")
        self.log.info("")

        passed_count = 0
        for name, passed, detail in self.results:
            tag = "PASS" if passed else "FAIL"
            self.log.info(f"[{tag}] {name}")
            if detail:
                self.log.info(f"       {detail}")
            if passed:
                passed_count += 1

        # Offset statistics during iPerf load
        if self._load_stats:
            st = self._load_stats
            self.log.info("")
            self.log.info("  Offset Statistics (during iPerf load):")
            self.log.info(f"    Samples : {st['samples']}")
            self.log.info(f"    Mean    : {st['mean']:+.1f} ns")
            self.log.info(f"    Stdev   : {st['stdev']:.1f} ns")
            self.log.info(f"    Min     : {st['min']:+d} ns")
            self.log.info(f"    Max     : {st['max']:+d} ns")
            self.log.info(
                f"    Within ±{OFFSET_THRESHOLD_NS}ns: "
                f"{st['within']}/{st['samples']} ({st['pct']:.0f}%)"
            )

        # Offset statistics after iPerf stopped
        if self._post_iperf_stats:
            st = self._post_iperf_stats
            self.log.info("")
            self.log.info("  Offset Statistics (post-iPerf):")
            self.log.info(f"    Samples : {st['samples']}")
            self.log.info(f"    Mean    : {st['mean']:+.1f} ns")
            self.log.info(f"    Stdev   : {st['stdev']:.1f} ns")
            self.log.info(f"    Min     : {st['min']:+d} ns")
            self.log.info(f"    Max     : {st['max']:+d} ns")
            self.log.info(
                f"    Within ±{OFFSET_THRESHOLD_NS}ns: "
                f"{st['within']}/{st['samples']} ({st['pct']:.0f}%)"
            )

        total = len(self.results)
        overall = "PASS" if passed_count == total else "FAIL"
        self.log.info("")
        self.log.info(
            f"Overall Result: {overall} ({passed_count}/{total} tests passed)"
        )

        if self.log.log_file:
            self.log.info(f"Log saved to  : {self.log.log_file}")

        return 0 if passed_count == total else 1


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    """Construct and return the CLI argument parser."""
    parser = argparse.ArgumentParser(
        description=(
            "iPerf PTP Test Agent for T1S 100BaseT Bridge\n"
            "Tests PTP convergence and stability under iPerf UDP load."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "--gm-port",
        default=DEFAULT_GM_PORT,
        metavar="PORT",
        help=f"Grandmaster COM port (default: {DEFAULT_GM_PORT})",
    )
    parser.add_argument(
        "--fol-port",
        default=DEFAULT_FOL_PORT,
        metavar="PORT",
        help=f"Follower COM port (default: {DEFAULT_FOL_PORT})",
    )
    parser.add_argument(
        "--gm-ip",
        default=DEFAULT_GM_IP,
        metavar="IP",
        help=f"GM IP address (default: {DEFAULT_GM_IP})",
    )
    parser.add_argument(
        "--fol-ip",
        default=DEFAULT_FOL_IP,
        metavar="IP",
        help=f"Follower IP address (default: {DEFAULT_FOL_IP})",
    )
    parser.add_argument(
        "--samples",
        type=int,
        default=DEFAULT_SAMPLES,
        metavar="N",
        help=f"Offset samples to collect during iPerf load (default: {DEFAULT_SAMPLES})",
    )
    parser.add_argument(
        "--post-iperf-samples",
        type=int,
        default=DEFAULT_POST_IPERF_SAMPLES,
        metavar="N",
        help=(
            f"Offset samples to collect after iPerf stops "
            f"(default: {DEFAULT_POST_IPERF_SAMPLES})"
        ),
    )
    parser.add_argument(
        "--convergence-timeout",
        type=float,
        default=DEFAULT_CONVERGENCE_TIMEOUT,
        metavar="S",
        help=(
            f"Max seconds to wait for FINE state "
            f"(default: {DEFAULT_CONVERGENCE_TIMEOUT})"
        ),
    )
    parser.add_argument(
        "--iperf-bandwidth",
        default=DEFAULT_IPERF_BANDWIDTH,
        metavar="BW",
        help=f"iPerf target bandwidth, e.g. 1M or 10M (default: {DEFAULT_IPERF_BANDWIDTH})",
    )
    parser.add_argument(
        "--iperf-duration",
        type=int,
        default=DEFAULT_IPERF_DURATION,
        metavar="S",
        help=f"iPerf client run time in seconds (default: {DEFAULT_IPERF_DURATION})",
    )
    parser.add_argument(
        "--iperf-port",
        type=int,
        default=DEFAULT_IPERF_PORT,
        metavar="PORT",
        help=f"UDP port used by iPerf (default: {DEFAULT_IPERF_PORT})",
    )
    parser.add_argument(
        "--from-step",
        type=int,
        default=1,
        metavar="N",
        choices=range(1, 11),
        help="Start from step N (1–10, default: 1)",
    )
    parser.add_argument(
        "--no-stop-ptp",
        dest="stop_ptp",
        action="store_false",
        help="Do not send 'ptp_mode off' on both boards after the test",
    )
    parser.add_argument(
        "--log-file",
        default=None,
        metavar="FILE",
        help=(
            "Log file path "
            "(default: auto-generated iperf_ptp_test_YYYYMMDD_HHMMSS.log)"
        ),
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose (debug) output",
    )

    return parser


def main() -> int:
    """Main entry-point.

    Returns:
        Exit code: ``0`` = all passed, ``1`` = any failed.
    """
    parser = build_arg_parser()
    args = parser.parse_args()

    # Capture a single start time so the log file name and the report header
    # are always consistent regardless of how long argument parsing takes.
    start_time = datetime.datetime.now()

    # Auto-generate log file name if not provided.
    log_file = args.log_file
    if log_file is None:
        log_file = f"iperf_ptp_test_{start_time.strftime('%Y%m%d_%H%M%S')}.log"

    log = Logger(log_file=log_file, verbose=args.verbose)

    agent = IperfPTPTestAgent(
        gm_port=args.gm_port,
        fol_port=args.fol_port,
        gm_ip=args.gm_ip,
        fol_ip=args.fol_ip,
        samples=args.samples,
        post_iperf_samples=args.post_iperf_samples,
        convergence_timeout=args.convergence_timeout,
        iperf_bandwidth=args.iperf_bandwidth,
        iperf_duration=args.iperf_duration,
        iperf_port=args.iperf_port,
        stop_ptp_after=args.stop_ptp,
        from_step=args.from_step,
        log=log,
    )

    try:
        exit_code = agent.run(start_time=start_time)
    finally:
        log.close()

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
