# PTP Convergence Test under iperf Load

This script tests the PTP convergence behavior under load generated by iperf.

## Description
- Tests PTP convergence behavior with network load from iperf
- Sequence: Start PTP follower, start iperf server on follower, start iperf client on master, then start PTP master
- Monitors convergence to FINE state under load
- Validates offset stability during network traffic
- Based on existing ptp_test_agent.py structure
- Includes background monitoring threads for iperf output
- Configurable iperf duration and port settings

## Instructions
1. Execute the script to start the test.
2. Ensure that the network is set up properly for iperf and PTP.
3. Analyze the output to verify convergence behavior.