# The following variables contains the files used by the different stages of the build process.
set(T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_assemble)
set_source_files_properties(${T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_assemble} PROPERTIES LANGUAGE ASM)

# For assembly files, add "." to the include path for each file so that .include with a relative path works
foreach(source_file ${T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_assemble})
        set_source_files_properties(${source_file} PROPERTIES INCLUDE_DIRECTORIES "$<PATH:NORMAL_PATH,$<PATH:REMOVE_FILENAME,${source_file}>>")
endforeach()

set(T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_assembleWithPreprocess)
set_source_files_properties(${T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_assembleWithPreprocess} PROPERTIES LANGUAGE ASM)

# For assembly files, add "." to the include path for each file so that .include with a relative path works
foreach(source_file ${T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_assembleWithPreprocess})
        set_source_files_properties(${source_file} PROPERTIES INCLUDE_DIRECTORIES "$<PATH:NORMAL_PATH,$<PATH:REMOVE_FILENAME,${source_file}>>")
endforeach()

set(T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_compile
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/app.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/crypto/src/crypto.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/ethphy/src/dynamic/drv_ethphy.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/ethphy/src/dynamic/drv_extphy_lan8740.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/gmac/src/dynamic/drv_gmac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/gmac/src/dynamic/drv_gmac_lib_samE5x.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/lan865x/src/dynamic/drv_lan865x_api.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/lan865x/src/dynamic/tc6/tc6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/miim/src/dynamic/drv_miim.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/miim/src/dynamic/drv_miim_gmac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/driver/spi/src/drv_spi.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/exceptions.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/initialization.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/interrupts.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/libc_syscalls.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/arp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/dhcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/dns.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/hash_fnv.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/helpers.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/icmp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/iperf.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/ipv4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/oahash.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_commands.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_heap_alloc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_heap_internal.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_helpers.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_mac_bridge.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_manager.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_notify.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/tcpip_packet.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/telnet.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/library/tcpip/src/udp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/net_pres/pres/net_pres_cert_store.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/net_pres/pres/net_pres_enc_glue.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/net_pres/pres/src/net_pres.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/clock/plib_clock.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/cmcc/plib_cmcc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/dmac/plib_dmac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/evsys/plib_evsys.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/nvic/plib_nvic.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/nvmctrl/plib_nvmctrl.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/port/plib_port.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/sercom/spi_master/plib_sercom0_spi_master.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/sercom/usart/plib_sercom1_usart.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/peripheral/tc/plib_tc0.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/startup_xc32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/stdio/xc32_monitor.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/cache/sys_cache.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/command/src/sys_command.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/console/src/sys_console.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/console/src/sys_console_uart.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/debug/src/sys_debug.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/dma/sys_dma.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/int/src/sys_int.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/reset/sys_reset.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/sys_random_h2_adapter.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/sys_time_h2_adapter.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/system/time/src/sys_time.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/config/default/tasks.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/main.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/aes.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/arc4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/asm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/asn.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/blake2b.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/blake2s.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/camellia.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/chacha.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/chacha20_poly1305.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/cmac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/coding.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/compress.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/cpuid.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/cryptocb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/curve25519.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/curve448.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/des3.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/dh.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/dsa.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ecc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ecc_fp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/eccsi.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ed25519.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ed448.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/error.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/evp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/falcon.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/fe_448.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/fe_low_mem.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/fe_operations.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ge_448.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ge_low_mem.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ge_operations.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/hash.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/hmac.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/integer.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/kdf.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/logging.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/md2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/md4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/md5.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/memory.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/misc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/pkcs12.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/pkcs7.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/poly1305.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_aes_sam6149.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_aes_u2238.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_ecc_ba414e.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_ecc_pukcl.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_pukcl_functions.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_rng_sam6334.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_rng_u2242.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_rsa_pukcl.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sam_u2803.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha1_sam11105.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha1_sam6156.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha224_sam11105.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha224_sam6156.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha256_sam11105.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha256_sam6156.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha384_sam6156.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_sha512_sam6156.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_tdes_sam6150.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/crypt_wolfcryptcb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/port/pic32/pic32mz-crypt.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/pwdbased.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/random.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/rc2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/ripemd.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/rsa.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sakke.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sha.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sha256.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sha3.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sha512.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/signature.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/siphash.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_arm32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_arm64.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_armthumb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_c32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_c64.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_cortexm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_dsp32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_int.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/sp_x86_64.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/srp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/tfm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/wc_dsp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/wc_encrypt.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/wc_pkcs11.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/wc_port.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/wolfevent.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../../src/third_party/wolfssl/wolfssl/wolfcrypt/src/wolfmath.c")
set_source_files_properties(${T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_compile} PROPERTIES LANGUAGE C)
set(T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_compile_cpp)
set_source_files_properties(${T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_compile_cpp} PROPERTIES LANGUAGE CXX)
set(T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_link)
set(T1S_100BaseT_Bridge_default_default_XC32_FILE_TYPE_bin2hex)
set(T1S_100BaseT_Bridge_default_image_name "default.elf")
set(T1S_100BaseT_Bridge_default_image_base_name "default")

# The output directory of the final image.
set(T1S_100BaseT_Bridge_default_output_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../../out/T1S_100BaseT_Bridge")

# The full path to the final image.
set(T1S_100BaseT_Bridge_default_full_path_to_image ${T1S_100BaseT_Bridge_default_output_dir}/${T1S_100BaseT_Bridge_default_image_name})
